version: 0.0  # CodeDeploy의 버전을 명시
os: linux
files:
  - source: / # 이동시킬 대상을 지정 (루트)
    destination: /home/ec2-user/app/step2/zip/  # 소스에서 지정된 파일을 받을 위치
    overwrite: yes

# CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포단계에서 실행할 명령어를 지정한다.
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user